apiVersion: v1
kind: Service
metadata:
  name: automated-rollback-system-service
spec:
  selector:
    app: automated-rollback-system
    version: my-app-blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP